on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      # fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0


      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git base-devel mingw-w64-${{ matrix.arch }}-toolchain gtk-doc
          update: true


      - name: add sig
        run: |
          set MSYSTEM=MSYS
          msys2 -c 'gpg --keyserver keyserver.ubuntu.com --recv-keys D605848ED7E69871'
          msys2 -c 'gpg --list-keys'
          
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: test
        shell: msys2 {0}
        run: |
          cd /C/_
          cd mingw-w64-gnutls
          MINGW_INSTALLS=${{ matrix.msystem }} makepkg -s --noconfirm

          
